In [25]:
#1. Start by importing NumPy as np


import numpy as np

In [26]:
# All of Alize’s recipes call for milk, eggs, sugar, flour, and butter. For example, her cupcake recipe calls for:
#Flour Sugar Eggs Milk Butter 2 cups 0.75 cups 2 eggs 1 cups 0.5 cups Create a NumPy array that represents this data. Each element should be a number (i.e., 2 for “2 cups”). Save this array as cupcakes.


cupcakes = np.array([2,0.75,2,1,0.5])
cupcakes

array([2.  , 0.75, 2.  , 1.  , 0.5 ])

In [31]:
#Alize’s assistant has compiled all of her recipes into a csv (comma-separated variable) file called recipes.csv. Load this file into a variable called recipes.
#####Explore yourselves how to load a csv file in numpy

from numpy import loadtxt 

recipes = np.loadtxt(open('Recipes.csv', 'rb'), delimiter=',')
recipes

array([[2.   , 0.75 , 2.   , 1.   , 0.5  ],
       [1.   , 0.125, 1.   , 1.   , 0.125],
       [2.75 , 1.5  , 1.   , 0.   , 1.   ],
       [4.   , 0.5  , 2.   , 2.   , 0.5  ]])

In [28]:
# 4.Display recipes using print. Display recipes using print.

#Each row represents a different recipe. Each column represents a different ingredient.

# Recipe Cups of Flour Cups of Sugar Eggs Cups of Milk Cups of Butter

# Cupcakes … … … … …

# Pancake … … … … …

# Cookie … … … … …

# Bread … … … … …

print('Cupcakes:',recipes[0,:])
print('Pancakes:',recipes[1,:])
print('Cookie:',recipes[2,:])
print('Bread:',recipes[3,:])



Cupcakes: [2.   0.75 2.   1.   0.5 ]
Pancakes: [1.    0.125 1.    1.    0.125]
Cookie: [2.75 1.5  1.   0.   1.  ]
Bread: [4.  0.5 2.  2.  0.5]


In [29]:
# 5.The 3rd column represents the number of eggs that each recipe needs.

# Select all elements from the 3rd column and save them to the variable eggs.

eggs = recipes[:,2]
eggs


array([2., 1., 1., 2.])

In [30]:
# 6.Which recipes require exactly 1 egg? Use a logical statement to get True or False for each value of eggs.

mask = (eggs == 1)
print(mask)
print(f'Pancake: {recipes[mask][0]}')
print(f'Cookie: {recipes[mask][1]}')
recipes[mask]

[False  True  True False]
Pancake: [1.    0.125 1.    1.    0.125]
Cookie: [2.75 1.5  1.   0.   1.  ]


array([[1.   , 0.125, 1.   , 1.   , 0.125],
       [2.75 , 1.5  , 1.   , 0.   , 1.   ]])

In [32]:

# 7.Alize is going to make 2 batches of cupcakes (1st row) and 1 batch of cookies (3rd row).

# You already have a variable for cupcakes. Create a variable for cookies with the data from the 3rd row.

cookies = recipes[2,:]
cookies

array([2.75, 1.5 , 1.  , 0.  , 1.  ])

In [33]:
#8. Get the number of ingredients for a double batch of cupcakes by using multiplication on cupcakes. Save your new variable to double_batch.

double_batch = cupcakes*2
double_batch

array([4. , 1.5, 4. , 2. , 1. ])

In [34]:
# 9. Create a new variable called grocery_list by adding cookies and double_batch.


grocery_list = cookies+double_batch
grocery_list

array([6.75, 3.  , 5.  , 2.  , 2.  ])