In [3]:
# Question:1 Convert a 1D array to a 2D array with 2 rows?  Desired output::¶ array([[0, 1, 2, 3, 4], [5, 6, 7, 8, 9]])

import numpy as np

a=np.array([[0, 1, 2, 3, 4],[5, 6, 7, 8, 9]])
(a)


array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [5]:
# Question:2 How to stack two arrays vertically?  Desired Output:: array([[0, 1, 2, 3, 4], [5, 6, 7, 8, 9], [1, 1, 1, 1, 1], [1, 1, 1, 1, 1]])

a=np.array([[0, 1, 2, 3, 4],[5, 6, 7, 8, 9], [1, 1, 1, 1, 1], [1, 1, 1, 1, 1]])
np.vstack(a)

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [6]:
# Question:3  How to stack two arrays horizontally? Desired Output:: array([[0, 1, 2, 3, 4, 1, 1, 1, 1, 1], [5, 6, 7, 8, 9, 1, 1, 1, 1, 1]])

a=np.array([[0, 1, 2, 3, 4, 1, 1, 1, 1, 1], [5, 6, 7, 8, 9, 1, 1, 1, 1, 1]])
np.hstack(a)

array([0, 1, 2, 3, 4, 1, 1, 1, 1, 1, 5, 6, 7, 8, 9, 1, 1, 1, 1, 1])

In [8]:
# Question:4 How to convert an array of arrays into a flat 1d array? Desired Output:: array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

a=np.array([[0,1,2,3,4,5,6,7,8,9],[0,1,2,3,4,5,6,7,8,9]])
print('\n',a,'\n')
print(a.ravel())
print(a.flatten())


 [[0 1 2 3 4 5 6 7 8 9]
 [0 1 2 3 4 5 6 7 8 9]] 

[0 1 2 3 4 5 6 7 8 9 0 1 2 3 4 5 6 7 8 9]
[0 1 2 3 4 5 6 7 8 9 0 1 2 3 4 5 6 7 8 9]


In [10]:
# Question:5 How to Convert higher dimension into one dimension? Desired Output:: array([ 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14])

a=np.array([ 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14])
a.reshape(5,3)

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

In [22]:
# Question:6 Convert one dimension to higher dimension? Desired Output:: array([[ 0, 1, 2], [ 3, 4, 5], [ 6, 7, 8], [ 9, 10, 11], [12, 13, 14]])

a=np.array([[ 0, 1, 2], [ 3, 4, 5], [ 6, 7, 8], [ 9, 10, 11], [12, 13, 14]])
a.flatten(order='a')

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [24]:
# Question:7 Create 5x5 an array and find the square of an array?

a=np.random.normal((5,5))
print(a,'\n')
print(np.sqrt(a))

[5.27180312 5.71461948] 

[2.29604075 2.39052703]


In [31]:
# Question:8 Create 5x6 an array and find the mean?

a=np.random.gamma((5,6))
print(a)
print('\n',a.mean())

[6.04559151 4.91486481]

 5.48022816076235


In [37]:
# Question:9 Find the standard deviation of the previous array in Q8?

np.std(a)

0.5653633462081933

In [38]:
# Question:10 Find the median of the previous array in Q8?
np.median(a)

5.48022816076235

In [39]:
# Question:11 Find the transpose of the previous array in Q8?

np.transpose(a)

array([6.04559151, 4.91486481])

In [43]:
# Question:12 Create a 4x4 an array and find the sum of diagonal elements?

array=np.arange(16).reshape(4,4)
print(array)
('Sum =',np.trace(array))

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]


('Sum =', 30)

In [48]:
# Question:13 Find the determinant of the previous array in Q12?

print(np.linalg.det(array))

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
-2.9582283945787796e-30


In [53]:
# Question:14 Find the 5th and 95th percentile of an array?

print(array)
print('\n',np.percentile(array,5))
print(np.percentile(array,95))

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]

 0.75
14.25


In [54]:
# Question:15 How to find if a given array has any null values?

print(array)
print('\n',np.isnan(array))


[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]

 [[False False False False]
 [False False False False]
 [False False False False]
 [False False False False]]
