In [183]:
# Import the numpy package under the name np
import numpy as np

In [38]:
# Create a null vector of size 10
Zero=np.zeros((10,10))
print (Zero)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


In [184]:
# Create a vector with values ranging from 10 to 49
Vector=np.arange(10,50)
print(Vector)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


In [40]:
# Find the shape of previous array in question 3
Vector.shape             

(40,)

In [42]:
# Print the type of the previous array in question 3
print(type(Vector)) 
print(Vector.dtype)

<class 'numpy.ndarray'>
int32


In [44]:
# Print the numpy version and the configuration
print(np.version.version)
print(np.show_config())

1.18.1
blas_mkl_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/Dell/anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl\\include', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl\\lib', 'C:/Users/Dell/anaconda3\\Library\\include']
blas_opt_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/Dell/anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl\\include', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl\\li

In [45]:
# Print the dimension of the array in question 3
print(Vector)
Vector.ndim

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


1

In [46]:
# Create a boolean array with all the True values
Vector = np.array([27, 27, 27, 27, 27, 27, 27])
print(Vector == 27)

[ True  True  True  True  True  True  True]


In [48]:
# Create a two dimensional array
Vector=np.array([[9,0,9,9],[9,9,0,9]])
Vector

array([[9, 0, 9, 9],
       [9, 9, 0, 9]])

In [50]:
# Create a three dimensional array
Vector=np.array([[9,0,9,9],[9,9,0,9],[1,4,7,1]])
Vector

array([[9, 0, 9, 9],
       [9, 9, 0, 9],
       [1, 4, 7, 1]])

In [185]:
# Reverse a vector (first element becomes last)
Vector=np.array([1,2,3,4,5])
print(Vector)
print (Vector[-1::-1])

[1 2 3 4 5]
[5 4 3 2 1]


In [70]:
# Create a null vector of size 10 but the fifth value which is 1
Vector=np.zeros(10)
Vector[4]=1
print (Vector)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


In [77]:
# Create a 3x3 identity matrix
Vector=np.eye(3,3)
print (Vector)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [186]:
# arr = np.array([1, 2, 3, 4, 5]) Convert the data type of the given array from int to float
arr = np.array([1, 2, 3, 4, 5])
print(arr.dtype)
arr = np.array([1, 2, 3, 4, 5])*2.00
print(arr.dtype)
arr = arr.astype('float64')
print (arr)

int32
float64
[ 2.  4.  6.  8. 10.]


In [97]:
# arr1 = np.array([[1., 2., 3.],[4., 5., 6.]])  arr2 = np.array([[0., 4., 1.],[7., 2., 12.]])  Multiply arr1 with arr2
arr1 = np.array([[1., 2., 3.],[4., 5., 6.]])  
arr2 = np.array([[0., 4., 1.],[7., 2., 12.]])
arr1*arr2

array([[ 0.,  8.,  3.],
       [28., 10., 72.]])

In [187]:
# arr1 = np.array([[1., 2., 3.],[4., 5., 6.]])  arr2 = np.array([[0., 4., 1.],[7., 2., 12.]])Make an array by comparing both the arrays provided above
arr1 = np.array([[1., 2., 3.],[4., 5., 6.]])  
arr2 = np.array([[0., 4., 1.],[7., 2., 12.]])
arr=arr1==arr2
arr

array([[False, False, False],
       [False, False, False]])

In [115]:
#Extract all odd numbers from arr with values(0-9)
arr=np.arange(0,10,3)
arr

array([0, 3, 6, 9])

In [118]:
# Replace all odd numbers to -1 from previous array
arr=np.arange(0,10,2)
arr

array([0, 2, 4, 6, 8])

In [188]:
#  arr = np.arange(10)  Replace the values of indexes 5,6,7 and 8 to 12
arr = np.arange(10)
a=np.arange(0,15)
a[5]=12
a[6]=12
a[7]=12
a[8]=12
a

array([ 0,  1,  2,  3,  4, 12, 12, 12, 12,  9, 10, 11, 12, 13, 14])

In [126]:
# Create a 2d array with 1 on the border and 0 inside
ar_2d=np.eye(5,5)
ar_2d

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [189]:
# arr2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]] Replace the value 5 to 12
arr2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
arr2d[1][1]=12
arr2d

array([[ 1,  2,  3],
       [ 4, 12,  6],
       [ 7,  8,  9]])

In [132]:
# arr3d = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]]) Convert all the values of 1st array to 64
arr3d = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
arr3d[0]=64
arr3d

array([[[64, 64, 64],
        [64, 64, 64]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [134]:
# Make a 2-Dimensional array with values 0-9 and slice out the first 1st 1-D array from it
arr2d=np.array([[0,1,2,3,4],[5,6,7,8,9]])
arr2d[0][0:5]

array([0, 1, 2, 3, 4])

In [139]:
# Make a 2-Dimensional array with values 0-9 and slice out the 2nd value from 2nd 1-D array from it
arr2d=np.array([[0,1,2,3,4],[5,6,7,8,9]])
arr2d[1][1]

6

In [190]:
# Make a 2-Dimensional array with values 0-9 and slice out the third column but only the first two rows
t_d=np.array([[0,1,2,3,4],[5,6,7,8,9]])
print(t_d)
print('\n',t_d[:3:,2])

[[0 1 2 3 4]
 [5 6 7 8 9]]

 [2 7]


In [196]:
# Create a 10x10 array with random values and find the minimum and maximum values
r_a=np.random.randint((10,10))
print('random numbers are ',r_a)
print(r_a.max())
print(r_a.min())

random numbers are  [8 3]
8
3


In [149]:
# Find the common items between a and b
a= np.array([1,2,3,2,3,4,3,4,5,6]) 
print(a)
b = np.array([7,2,10,2,7,4,9,4,9,8])
print(b)
print("Common values between two arrays:")
print(np.intersect1d(a,b))

[1 2 3 2 3 4 3 4 5 6]
[ 7  2 10  2  7  4  9  4  9  8]
Common values between two arrays:
[2 4]


In [150]:
# Find the positions where elements of a and b match
a= np.array([1,2,3,2,3,4,3,4,5,6]) 
b = np.array([7,2,10,2,7,4,9,4,9,8])
np.where(a==b)

(array([1, 3, 5, 7], dtype=int64),)

In [155]:
# Find all the values from array data where the values from array names are not equal to Will
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])
data = np.random.randn(7, 4)
print (data)
print ('\n',data[names!="Will"])

[[ 0.52767295 -0.05066476 -0.15120303 -2.08756103]
 [ 0.32272609 -1.5886565   1.01615832  0.15836287]
 [ 0.58231971  0.1312906  -0.46344482  0.72089446]
 [-0.9882208   0.62379616  1.21777259  1.06265756]
 [-0.65706092 -0.94339208  1.89388673  0.44982359]
 [ 0.80662941  1.18067642 -1.35430857 -0.66959376]
 [-0.81086085  1.46821152  0.57939667  0.59301559]]

 [[ 0.52767295 -0.05066476 -0.15120303 -2.08756103]
 [ 0.32272609 -1.5886565   1.01615832  0.15836287]
 [-0.9882208   0.62379616  1.21777259  1.06265756]
 [ 0.80662941  1.18067642 -1.35430857 -0.66959376]
 [-0.81086085  1.46821152  0.57939667  0.59301559]]


In [195]:
# Find all the values from array data where the values from array names are not equal to Will and Joe
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])
data = np.random.randn(7, 4)
print (data)
print ('\n',data[names!="'Will', 'joe'"])

[[ 1.52932082 -0.28094172 -0.70679287 -0.10226216]
 [ 0.27406815 -1.46975353  0.08523305  1.86545199]
 [-0.16738756 -1.61408605 -1.16369313  0.36525565]
 [-0.54291812 -1.31783215 -1.26903384 -1.19339821]
 [ 0.72402937  1.09505177  0.91591081  0.70501317]
 [-0.4493355   0.47227444 -0.2446419  -0.45789641]
 [ 0.54558556 -0.3628969  -1.21563872 -1.4681903 ]]

 [[ 1.52932082 -0.28094172 -0.70679287 -0.10226216]
 [ 0.27406815 -1.46975353  0.08523305  1.86545199]
 [-0.16738756 -1.61408605 -1.16369313  0.36525565]
 [-0.54291812 -1.31783215 -1.26903384 -1.19339821]
 [ 0.72402937  1.09505177  0.91591081  0.70501317]
 [-0.4493355   0.47227444 -0.2446419  -0.45789641]
 [ 0.54558556 -0.3628969  -1.21563872 -1.4681903 ]]


In [158]:
# Create a 2D array of shape 5x3 to contain decimal numbers between 1 and 15
t_d=np.arange(1,16).reshape(5,3)
print (t_d)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]
 [13 14 15]]


In [159]:
# Create an array of shape (2, 2, 4) with decimal numbers between 1 to 16.
t_d=np.arange(1,17,1).reshape(2,2,4)
t_d

array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8]],

       [[ 9, 10, 11, 12],
        [13, 14, 15, 16]]])

In [160]:
# Swap axes of the array you created in Question 32
t_d[0][1]=t_d[1][0]
t_d

array([[[ 1,  2,  3,  4],
        [ 9, 10, 11, 12]],

       [[ 9, 10, 11, 12],
        [13, 14, 15, 16]]])

In [162]:
# Create an array of size 10, and find the square root of every element in the array, if the values less than 0.5, replace them with 0
sq=np.random.randint(10)
print(sq)
print(np.sqrt(sq))
print(np.where(sq<0.5,0,1))

6
2.449489742783178
1


In [164]:
#Create two random arrays of range 12 and make an array with the maximum values between each element of the two arrays
a=np.array(np.random.rand(12))
b=np.array(np.random.rand(12))
print('\n',a)
print('\n',b)
print('\n',np.where(a>b,a,b))
print('\n',np.where(b>a,b,a))


 [0.04550657 0.73424981 0.40410528 0.70055969 0.90076193 0.44917068
 0.22641502 0.19711602 0.82548928 0.56456122 0.36336019 0.81494847]

 [0.00096442 0.60540774 0.54383383 0.53796631 0.65252376 0.71231116
 0.38863068 0.02891144 0.32505875 0.12527621 0.50160355 0.54113027]

 [0.04550657 0.73424981 0.54383383 0.70055969 0.90076193 0.71231116
 0.38863068 0.19711602 0.82548928 0.56456122 0.50160355 0.81494847]

 [0.04550657 0.73424981 0.54383383 0.70055969 0.90076193 0.71231116
 0.38863068 0.19711602 0.82548928 0.56456122 0.50160355 0.81494847]


In [194]:
# Find the unique names and sort them out!
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])
np.unique(names)

array(['Bob', 'Joe', 'Will'], dtype='<U4')

In [193]:
# a = np.array([1,2,3,4,5])  b = np.array([5,6,7,8,9])   From array a remove all items present in array b
a = np.array([1,2,3,4,5])
b = np.array([5,6,7,8,9])
print(a!=b)
print('\n',np.setdiff1d(a,b))

[ True  True  True  True  True]

 [1 2 3 4]


In [192]:
# Following is the input NumPy array delete column two and insert following new column in its place sampleArray=np.array([[34,43,73],[82,22,12],[53,94,66]])     newColumn = np.array([[10,10,10]]) 
sampleArray=np.array([[34,43,73],[82,22,12],[53,94,66]])
newColumn = np.array([[10,10,10]])
print (sampleArray)
(sampleArray[:3,:2])

[[34 43 73]
 [82 22 12]
 [53 94 66]]


array([[34, 43],
       [82, 22],
       [53, 94]])

In [191]:
# x = np.array([[1., 2., 3.], [4., 5., 6.]]) y = np.array([[6., 23.], [-1, 7], [8, 9]])Find the dot product of the above two matrix
x = np.array([[1., 2., 3.], [4., 5., 6.]])
y = np.array([[6., 23.], [-1, 7], [8, 9]])
np.dot(x,y)

array([[ 28.,  64.],
       [ 67., 181.]])

In [182]:
# Generate a matrix of 20 random values and find its cumulative sum
Matrix=np.random.randn(20)
print('\n',Matrix.cumsum())


 [-5.36358108e-01 -1.35948908e+00 -5.29692235e-01 -1.98889605e-01
 -8.22978577e-01 -1.05065141e+00 -1.79637455e+00 -1.77173365e+00
 -1.11099918e-01 -6.90308249e-01 -5.55049356e-01 -2.06004928e-01
  1.83694325e-04 -2.92470089e-01 -1.68281333e+00 -1.41057775e+00
  7.48326393e-02 -1.62206888e-01  2.30138705e-01 -5.34189290e-02]
